from setuptools import setup
#  sudo apt install -y python3-certifi python3-chardet python3-google-auth python3-decorator python3-h5py python3-idna python3-imageio python3-joblib python3-Keras-Preprocessing python3-Markdown python3-matplotlib python3-networkx python3-numpy python3-oauthlib python3-pandas python3-protobuf python3-pyasn1 python3-pyasn1-modules python3-pyparsing python3-requests python3-requests-oauthlib python3-rsa python3-scikit-learn python3-scipy python3-six python3-tensorflow python3-tensorflow-estimator python3-termcolor python3-urllib3 python3-Werkzeug python3-wrapt python3-zipp
setup(
    name='navsea',
    version='5.1',
    packages=['navsea', 'navsea.corrosion', 'navsea.denoisenet', 'navsea.biofouling'],
    url='',
    license='mit open source',
    author='giavo',
    author_email='tul55523@temple.edu',
    description='biofouling and corrosion detection',
    install_requires = ["absl-py>=0.11.0",
                        "astunparse>=1.6.3",
                        "cached-property>=1.5.2",
                        "cachetools>=4.1.1",
                       # "certifi>=2020.11.8",
                       # "chardet>=3.0.4",
                        "cycler>=0.10.0",
                        #"decorator>=4.4.2",
                        "gast>=0.3.3",
                       # "google-auth>=1.23.0",
                        "google-auth-oauthlib>=0.4.2",
                        "google-pasta>=0.2.0",
                        "grpcio>=1.34.0",
                        #"h5py>=2.10.0",
                        #"idna>=2.10",
                       # "imageio>=2.9.0",
                        "importlib-metadata>=3.1.1",
                        #"joblib>=0.17.0",
                        "Keras==2.4.3",
                        #"Keras-Preprocessing>=1.1.2",
                        "kiwisolver>=1.3.1",
                       # "Markdown>=3.3.3",
                       # "matplotlib>=3.3.3",
                       # "networkx>=2.5",
                       # "numpy==1.18.5",
                       # "oauthlib>=3.1.0",
                       # "opencv-python>=4.4.0.46",
                        "opt-einsum>=3.3.0",
                        #"pandas>=1.1.4",
                        "Pillow==8.0.1",
                        #"protobuf>=3.14.0",
                        #"pyasn1>=0.4.8",
                        #"pyasn1-modules>=0.2.8",
                        #"pyparsing>=2.4.7",
                        "python-dateutil>=2.8.1",
                        "pytz==2020.4",
                        "PyWavelets==1.1.1",
                        "PyYAML==5.3.1",
                        #"requests>=2.25.0",
                        #"requests-oauthlib>=1.3.0",
                        #"rsa>=4.6",
                        #"scikit-image==0.17.2",
                       # "scikit-learn==0.23.2",
                        #"scipy>=1.5.4",
                        #"six>=1.15.0",
                        "tensorboard==2.4.0",
                        "tensorboard-plugin-wit>=1.7.0",
                        #"tensorflow>=2.3.1",
                        #"tensorflow-estimator>=2.3.0",
                        #"termcolor>=1.1.0",
                        "threadpoolctl==2.1.0",
                        "tifffile==2020.9.3",
                        #"urllib3>=1.26.2",
                        #"Werkzeug>=1.0.1",
                        #"wrapt>=1.12.1",
                        #"zipp>=3.4.0"

] # Here we'll get: ["gunicorn", "docutils>=0.3", "lxml==0.5a7"]
)
